//Url
export const API_BASE_URL = "http://localhost:3000";

//Login
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Login
export const LOGIN_FETCH_REQUEST = "LOGIN_FETCH_REQUEST";
export const LOGIN_FETCH_SUCCESS = "LOGIN_FETCH_SUCCESS";
export const LOGIN_FETCH_FAIL = "LOGIN_FETCH_FAIL";

//Signup
export const REGISTER_FETCH_REQUEST = "REGISTER_FETCH_REQUEST";
export const REGISTER_FETCH_SUCCESS = "REGISTER_FETCH_SUCCESS";
export const REGISTER_FETCH_FAIL = "REGISTER_FETCH_FAIL";

//User
export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";

//Logout
export const LOGOUT = "LOGOUT";

//Usuario
export const USUARIO_FETCH_REQUEST = "USUARIO_FETCH_REQUEST";
export const USUARIO_FETCH_SUCCESS = "USUARIO_FETCH_SUCCESS";
export const USUARIO_FETCH_FAIL = "USUARIO_FETCH_FAIL";

//Telephone
export const TELEPHONE_FETCH_REQUEST = "TELEPHONE_FETCH_REQUEST";
export const TELEPHONE_FETCH_SUCCESS = "TELEPHONE_FETCH_SUCCESS";
export const TELEPHONE_FETCH_FAIL = "TELEPHONE_FETCH_FAIL";

//Desempleo
export const DESEMPLEO_FETCH_REQUEST = "DESEMPLEO_FETCH_REQUEST";
export const DESEMPLEO_FETCH_SUCCESS = "DESEMPLEO_FETCH_SUCCESS";
export const DESEMPLEO_FETCH_FAIL = "DESEMPLEO_FETCH_FAIL";

//Empresa
export const EMPRESA_FETCH_REQUEST = "EMPRESA_FETCH_REQUEST";
export const EMPRESA_FETCH_SUCCESS = "EMPRESA_FETCH_SUCCESS";
export const EMPRESA_FETCH_FAIL = "EMPRESA_FETCH_FAIL";

//Direccion
export const DIRECCION_FETCH_REQUEST = "DIRECCION_FETCH_REQUEST";
export const DIRECCION_FETCH_SUCCESS = "DIRECCION_FETCH_SUCCESS";
export const DIRECCION_FETCH_FAIL = "DIRECCION_FETCH_FAIL";

//Nombre
export const NOMBRE_FETCH_REQUEST = "NOMBRE_FETCH_REQUEST";
export const NOMBRE_FETCH_SUCCESS = "NOMBRE_FETCH_SUCCESS";
export const NOMBRE_FETCH_FAIL = "NOMBRE_FETCH_FAIL";

//Identificacion
export const IDENTIFICACION_FETCH_REQUEST = "IDENTIFICACION_FETCH_REQUEST";
export const IDENTIFICACION_FETCH_SUCCESS = "IDENTIFICACION_FETCH_SUCCESS";
export const IDENTIFICACION_FETCH_FAIL = "IDENTIFICACION_FETCH_FAIL";

//Experiencia
export const EXPERIENCIA_FETCH_REQUEST = "EXPERIENCIA_FETCH_REQUEST";
export const EXPERIENCIA_FETCH_SUCCESS = "EXPERIENCIA_FETCH_SUCCESS";
export const EXPERIENCIA_FETCH_FAIL = "EXPERIENCIA_FETCH_FAIL";

//Formacion
export const FORMACION_FETCH_REQUEST = "FORMACION_FETCH_REQUEST";
export const FORMACION_FETCH_SUCCESS = "FORMACION_FETCH_SUCCESS";
export const FORMACION_FETCH_FAIL = "FORMACION_FETCH_FAIL";

//Lenguajes
export const LENGUAJE_FETCH_REQUEST = "LENGUAJE_FETCH_REQUEST";
export const LENGUAJE_FETCH_SUCCESS = "LENGUAJE_FETCH_SUCCESS";
export const LENGUAJE_FETCH_FAIL = "LENGUAJE_FETCH_FAIL";

//referencias
export const REFERENCIA_FETCH_REQUEST = "REFERENCIA_FETCH_REQUEST";
export const REFERENCIA_FETCH_SUCCESS = "REFERENCIA_FETCH_SUCCESS";
export const REFERENCIA_FETCH_FAIL = "REFERENCIA_FETCH_FAIL";

//Solicitud Trabajo
export const SOLICITUDTRABAJO_FETCH_REQUEST = "SOLICITUDTRABAJO_FETCH_REQUEST";
export const SOLICITUDTRABAJO_FETCH_SUCCESS = "SOLICITUDTRABAJO_FETCH_SUCCESS";
export const SOLICITUDTRABAJO_FETCH_FAIL = "SOLICITUDTRABAJO_FETCH_FAIL";

//categoria empresa
export const CATEGORIAEMPRESA_FETCH_REQUEST = "CATEGORIAEMPRESA_FETCH_REQUEST";
export const CATEGORIAEMPRESA_FETCH_SUCCESS = "CATEGORIAEMPRESA_FETCH_SUCCESS";
export const CATEGORIAEMPRESA_FETCH_FAIL = "CATEGORIAEMPRESA_FETCH_FAIL";

//Nivel Carrera
export const NIVELCARRERA_FETCH_REQUEST = "NIVELCARRERA_FETCH_REQUEST";
export const NIVELCARRERA_FETCH_SUCCESS = "NIVELCARRERA_FETCH_SUCCESS";
export const NIVELCARRERA_FETCH_FAIL = "NIVELCARRERA_FETCH_FAIL";

//categoria trabajo
export const CATEGORIATRABAJO_FETCH_REQUEST = "CATEGORIATRABAJO_FETCH_REQUEST";
export const CATEGORIATRABAJO_FETCH_SUCCESS = "CATEGORIATRABAJO_FETCH_SUCCESS";
export const CATEGORIATRABAJO_FETCH_FAIL = "CATEGORIATRABAJO_FETCH_FAIL";

//Monedas
export const MONEDA_FETCH_REQUEST = "MONEDA_FETCH_REQUEST";
export const MONEDA_FETCH_SUCCESS = "MONEDA_FETCH_SUCCESS";
export const MONEDA_FETCH_FAIL = "MONEDA_FETCH_FAIL";

//CV
export const CV_FETCH_REQUEST = "CV_FETCH_REQUEST";
export const CV_FETCH_SUCCESS = "CV_FETCH_SUCCESS";
export const CV_FETCH_FAIL = "CV_FETCH_FAIL";

//Publicacion Trabajo
export const PUBLICACIONTRABAJO_FETCH_REQUEST =
  "PUBLICACIONTRABAJO_FETCH_REQUEST";
export const PUBLICACIONTRABAJO_FETCH_SUCCESS =
  "PUBLICACIONTRABAJO_FETCH_SUCCESS";
export const PUBLICACIONTRABAJO_FETCH_FAIL = "PUBLICACIONTRABAJO_FETCH_FAIL";

//CV
export const INTERVIEW_FETCH_REQUEST = "INTERVIEW_FETCH_REQUEST";
export const INTERVIEW_FETCH_SUCCESS = "INTERVIEW_FETCH_SUCCESS";
export const INTERVIEW_FETCH_FAIL = "INTERVIEW_FETCH_FAIL";